vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        advert_image:
            # Voir le fichier /config/services.yaml pour l'emplacement du %advert_image%
            uri_prefix: '%advert_image%'
            upload_destination: 'C:\Users\daoud\OneDrive\Images\Vich'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
